export const SCREEN = {
    HOME: "HOME",
    FILTER : "FILTER",
    CATEGORY: "CATEGORY",
    CATEGORY_RESULTS: "CATEGORY_RESULTS",
    CATEGORY_RESULT_ITEM: "CATEGORY_RESULT_ITEM",
    FAVORITE : "FAVORITE",

};